### ISSUE TITLE
Create a package

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Penguins#11]
Create a python package for the Penguins use case named `iceberg-penguins.search`.

**Comment by bspitzbart** [comment]
I posted the penguins package at: https://test.pypi.org/project/iceberg-penguins.search/
It installs fine with --no-deps, but still has issues when installing with the dependencies.

(pen_test2) [bspitzbart@login2 Penguins_package]$ python3 -m pip install --index-url https://test.pypi.org/simple/ iceberg-penguins.search
Looking in indexes: https://test.pypi.org/simple/
Collecting iceberg-penguins.search
  Downloading https://test-files.pythonhosted.org/packages/2e/1f/44747286aa1469238e8eb161c4d17d8e5b2cb61f8154313d59b670075b29/iceberg_penguins.search-0.2
     |ââââââââââââââââââââââââââââââââ| 71kB 1.4MB/s 
ERROR: Could not find a version that satisfies the requirement pytorch (from iceberg-penguins.search) (from versions: none)
ERROR: No matching distribution found for pytorch (from iceberg-penguins.search)
(pen_test2) [bspitzbart@login2 Penguins_package]$ python3 -m pip install --index-url https://test.pypi.org/simple/ --no-deps iceberg-penguins.search
Looking in indexes: https://test.pypi.org/simple/
Collecting iceberg-penguins.search
  Downloading https://test-files.pythonhosted.org/packages/2e/1f/44747286aa1469238e8eb161c4d17d8e5b2cb61f8154313d59b670075b29/iceberg_penguins.search-0.2
     |ââââââââââââââââââââââââââââââââ| 71kB 1.4MB/s 
Installing collected packages: iceberg-penguins.search
Successfully installed iceberg-penguins.search-0.2.4

**Comment by bspitzbart** [comment]
(this is just a note to myself, but if anyone has any clues let me know)
+Install from cloned repo in a fresh virtualenv:
(test) (base) [bspitz@login005 Penguins]$ pip install --upgrade --user .
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
(test) (base) [bspitz@login005 Penguins]$ deactivate
+outside virtualenv
(base) [bspitz@login005 Penguins]$ pip install --upgrade --user .
Processing /pylon5/mc3bggp/bspitz/Penguins_test/Penguins
Could not install packages due to an EnvironmentError: [('/pylon5/mc3bggp/bspitz/Penguins_test/Penguins/.git/objects/pack/pack-c560714430205677d64e9066e8b495468d5ef408.pack', '/tmp/pip-req-build-o1l_3kw4/.git/objects/pack/pack-c560714430205677d64e9066e8b495468d5ef408.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-o1l_3kw4/.git/objects/pack/pack-c560714430205677d64e9066e8b495468d5ef408.pack'"), ('/pylon5/mc3bggp/bspitz/Penguins_test/Penguins/.git/objects/pack/pack-c560714430205677d64e9066e8b495468d5ef408.idx', '/tmp/pip-req-build-o1l_3kw4/.git/objects/pack/pack-c560714430205677d64e9066e8b495468d5ef408.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-o1l_3kw4/.git/objects/pack/pack-c560714430205677d64e9066e8b495468d5ef408.idx'")]

**Comment by bspitzbart** [comment]
(another note to self)
+ will not install from pypi inside virtualenv, but does outside
(test) (base) [bspitz@login005 Penguins]$ pip install --upgrade iceberg-penguins.search==0.2.4.3
Traceback (most recent call last):
  File "/pylon5/mc3bggp/bspitz/Penguins_test/Penguins/test/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
ImportError: No module named 'pip._internal.cli'

**Comment by bspitzbart** [comment]
Last incompatibilities:
iceberg-penguins-search 0.2.4.4 has requirement scipy==0.19.0, but you'll have scipy 1.2.1 which is incompatible.
pandas 0.24.2 has requirement numpy>=1.12.0, but you'll have numpy 1.12.0b1 which is incompatible.
scikit-image 0.15.0 has requirement pillow>=4.3.0, but you'll have pillow 4.2.1 which is incompatible.
pywavelets 1.1.1 has requirement numpy>=1.13.3, but you'll have numpy 1.12.0b1 which is incompatible.
Installing collected packages: cycler, matplotlib, torch, lxml, Glymur, olefile, Pillow, torchvision, scipy, opencv-python, jsonpointer, jsonpatch, torchfile, websocket-client, visdom, shapely, docopt, pandas, pyproj, imageio, PyWavelets, decorator, networkx, scikit-image, gisrastertools, scikit-learn, iceberg-penguins.search
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/cycler.py'
Consider using the `--user` option or check the permissions.

**Comment by AymenFJA** [comment]
The Penguins package is available now via `pypi` [here](https://pypi.org/project/iceberg-penguins.search/).
